---
google_fonts:
    dest:
        fonts : static/externals/google_fonts/fonts
        css   : static/externals/google_fonts/css
    fonts:
        'Inter Tight':
            variants:
                - regular
                - italic
                - 700
                - 700italic
            subsets:
                - latin
                - latin-ext
            formats:
                - woff2
                - woff
                - ttf
    icons:
        types:
            - 'Material Symbols Outlined'
        formats:
            - woff2
            - woff
vue:
    dest: static/externals/vue
    libs:
        vue/dist/vue.global.js       : vue.global.js
        vue/dist/vue.global.prod.js  : vue.global.prod.js
        vue-demi                     : demi.iife.js
        pinia/dist/pinia.iife.js     : pinia.iife.js
        pinia/dist/pinia.iife.prod.js: pinia.iife.prod.js
