---
roster:
    tags:
        append : Youth
        default: Veteran
statistics:
    drop:
        type : lowest
        meets: [ 1, 2, 3 ]
    meets:
        - name  : Meet 1
          weight: 2
        - name  : Meet 2
          weight: 2
        - name  : Meet 3
          weight: 2
        - name  : Meet 4
          weight: 4
        - name  : Meet 5
          weight: 5
        - name  : Championships
          weight: 7
